### ISSUE TITLE
Batch InstallMilitaryToolsFoArcGISPro.bat is out of sync with Addin file name.

### ISSUE THREAD

**Issue by pshowalter** [Esri/military-tools-for-arcgis#18]
Batch file (or Addin) does not match.

InstallMilitaryToolsFoArcGISPro.bat is looking .\ArcGISPro\MilitaryToolsToolbar\ArcGISProAddinMAToolbar.esriAddInX
 however the the download I found contains  

.\current\ArcGISPro\Addins\MilitaryToolsToolbar\ArcGISProMAToolbar.esriAddInX

**Comment by mfunk** [comment]
Seeing this with the 5/4/2016 9:06 AM build (#330) pulled from
*\\redarchive2\disl\Development\Commercial\Military Tools For ArcGIS\current*

The message is:
![image](https://cloud.githubusercontent.com/assets/3093182/15027204/75f436c8-11f7-11e6-9c67-f717d7ddf170.png)

Looking into the **InstallMilitaryToolsFoArcGISPro.bat**:

```
C:
SET COMMONDIR="C:\Program Files (x86)\ArcGIS\Pro\bin"
IF NOT EXIST %COMMONDIR% SET COMMONDIR="C:\Program Files\ArcGIS\Pro\bin"
%COMMONDIR%\RegisterAddIn.exe /s Addins\CoordinateConversion\ProAppCoordConversionModule.esriAddInX
%COMMONDIR%\RegisterAddIn.exe /s Addins\DistanceAndDirection\ProAppDistanceAndDirectionModule.esriAddInX
%COMMONDIR%\RegisterAddIn.exe /s Addins\Visibility\ProAppVisibilityModule.esriAddInX
start %COMMONDIR%\RegisterAddIn.exe Addins\MilitaryToolsToolbar\ArcGISProAddinMAToolbar.esriAddInX
```

The problem I'm seeing is that the file that is to be registered is named:
**ArcGISProMAToolbar.esriAddInX**
and not
*ArcGISProAddinMAToolbar.esriAddInX*

(note the spelling difference)

The following change to the BAT file fixes the issue....

```
C:
SET COMMONDIR="C:\Program Files (x86)\ArcGIS\Pro\bin"
IF NOT EXIST %COMMONDIR% SET COMMONDIR="C:\Program Files\ArcGIS\Pro\bin"
%COMMONDIR%\RegisterAddIn.exe /s Addins\CoordinateConversion\ProAppCoordConversionModule.esriAddInX
%COMMONDIR%\RegisterAddIn.exe /s Addins\DistanceAndDirection\ProAppDistanceAndDirectionModule.esriAddInX
%COMMONDIR%\RegisterAddIn.exe /s Addins\Visibility\ProAppVisibilityModule.esriAddInX
start %COMMONDIR%\RegisterAddIn.exe Addins\MilitaryToolsToolbar\ArcGISProMAToolbar.esriAddInX
```

@ACueva 
@topowright 
@pshowalter

**Comment by csmoore** [comment]
I'll include an un-install batch as part of this fix so we can more easily uninstall and catch these problems (because I had built in studio I didn't even catch this when I updated the script)

**Comment by ACueva** [comment]
I thought we were shifting away from using "MA" in our product names.  
@topowright can you shed some light here please?

**Comment by pshowalter** [comment]
Batch file now calls the correct name for ArcGISProMAToolbar.esriAddInX.  

Q: Is using the silent install is best way to go in batch file; the batch file reports "Successfully Registered Pro Add-ins", whether the Add-in was installed or not.

**Comment by csmoore** [comment]
@pshowalter - the other 4 addins were already using a silent install option (so presumably had the same issue that you don't know if they work), so I just made the toolbar line look like the rest - I was under the impression that toolbar line with "start " was done that way because of a workaround on ArcMap only. 

But feel free to turn the silent- `\s` option off/on as desired - I didn't mean to change this behavior if it was intended.
