### ISSUE TITLE
Add Pro Symbol Editor

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-for-arcgis#20]
I didn't realize there was a Pro toolbar(tab?) so I suppose it is time to add the Symbol Editor to this tab & batch register file.

I guess this also answers the (unanswered) question I had here: 
https://github.com/Esri/military-symbol-editor-addin-wpf/issues/38

**Comment by dhagens** [comment]
Let me know if you have any issues adding the Symbol Editor to the MilitaryTools toolbar.  I was able to add it yesterday but want to make sure my instructions are adequate in the readme.
