### ISSUE TITLE
Batch file does not register ArcGIS Pro addins

### ISSUE THREAD

**Issue by ACueva** [Esri/military-tools-for-arcgis#22]
Installer shows the addins were successfully registered.  Once ArcGIS Pro 1.2 is opened, no addins are present.

Environment: WIndows 10
Version: ArcGIS Pro 1.2

Tried running with elevated administrator permissions, same result.

The uninstall batch file works fine.

```command
C:\WINDOWS\system32>C:

C:\WINDOWS\system32>SET PRO_DIR="C:\Program Files\ArcGIS\Pro\bin"

C:\WINDOWS\system32>IF NOT EXIST "C:\Program Files\ArcGIS\Pro\bin" SET PRO_DIR="C:\Users\avel5840\AppData\Local\Programs\ArcGIS\Pro\bin"

C:\WINDOWS\system32>IF EXIST "C:\Program Files\ArcGIS\Pro\bin" goto pro_exists_ok

C:\WINDOWS\system32>"C:\Program Files\ArcGIS\Pro\bin"\RegisterAddIn.exe /s Addins\CoordinateConversion\ProAppCoordConversionModule.esriAddInX

C:\WINDOWS\system32>"C:\Program Files\ArcGIS\Pro\bin"\RegisterAddIn.exe /s Addins\DistanceAndDirection\ProAppDistanceAndDirectionModule.esriAddInX

C:\WINDOWS\system32>"C:\Program Files\ArcGIS\Pro\bin"\RegisterAddIn.exe /s Addins\Visibility\ProAppVisibilityModule.esriAddInX

C:\WINDOWS\system32>"C:\Program Files\ArcGIS\Pro\bin"\RegisterAddIn.exe /s Addins\MilitarySymbolEditor\ProSymbolEditor.esriAddInX

C:\WINDOWS\system32>"C:\Program Files\ArcGIS\Pro\bin"\RegisterAddIn.exe /s Addins\MilitaryToolsToolbar\ArcGISProMAToolbar.esriAddInX

C:\WINDOWS\system32>echo Successfully Registered Pro Add-ins
Successfully Registered Pro Add-ins

C:\WINDOWS\system32>pause
Press any key to continue . . .

**Comment by dhagens** [comment]
Tested this this morning and everything seems to be working fine.  Please retest.

**Comment by dhagens** [comment]
I am running on Windows 7 though.  Not sure if 10 is the issue.

**Comment by csmoore** [comment]
@ACueva - since I'm the last one to touch/break I can also checkout what might be going wrong on your machine (I tested with Windows 10) - just ping

**Comment by ACueva** [comment]
The issue appears when I try to run the script from a network share.  If I copy the directory to my local machine it is a non issue.
The work-around to this issue is to remove this line:
https://github.com/Esri/military-tools-for-arcgis/blob/dev/source/MilitaryToolsToolbar/ArcGISProAddinMAToolbar/InstallMilitaryToolsFoArcGISPro.bat#L1

Replace it with:
```command
pushd %~dp0 
```

The only issue is for the ArcMap batch install file has a 
``` command
start
```
in
```
start %COMMONDIR%\ESRIRegAddIn.exe Addins\MilitaryToolsToolbar\ArcMapAddinMAToolbar.esriAddIn
```
that causes the script to fail.
 https://github.com/Esri/military-tools-for-arcgis/blob/dev/source/MilitaryToolsToolbar/ArcMapAddinMAToolbar/InstallMilitaryToolsForArcMap.bat#L7

**Comment by csmoore** [comment]
@dhagens @jmccausland @topowright - do you recall why the `start` was added to `start ESRIRegAddIn.exe Addins\MilitaryToolsToolbar\ArcMapAddinMAToolbar.esriAddIn` line. Can it be removed (I removed it from the Pro version of the script)? It seemed to work fine for Avi without the extra `start` and removing this is the only other thing needed to resolve this issue.

**Comment by jmccausland** [comment]
Without the start in the ArcMap version on a Win7 machine, the user would not be able to see the install dialog for the addIn.  I have not been involved with testing the Pro version.  

Is this just for Jenkins?

**Comment by dhagens** [comment]
It will work either way, but like Joe said, no confirmation dialog w/o the start for the MilitaryTool Add-In.

[cid:image001.png@01D1AAD1.BCF42A20]

**Comment by csmoore** [comment]
The change is mainly so people can run directly from the network share of the build `\\{buildshare}\Military Tools For ArcGIS\current` 

On both Windows 7 and 10 we didn't noticed a difference - without `\s` silent - we get the confirmation pop-up

**Comment by dhagens** [comment]
Test with and w/o the start using the /s.  You will see different results.  That’s how it works for me on Windows 7.  If the confirmation popup for the Add-In install is not necessary, we can get rid of the start.

**Comment by ACueva** [comment]
@csmoore @dhagens perhaps this should be assigned to someone?

**Comment by ACueva** [comment]
Verified by running directly from a network drive.
