### ISSUE TITLE
Coordinate Conversion in ArcGIS Pro Issue

### ISSUE THREAD

**Issue by joebayles** [Esri/military-tools-for-arcgis#33]
## Expected Behavior

When typing in an MGRS coordinate string, the Coordinate Conversion Add-In will accurately display the location and convert to another supported coordinate system.
When using a four-digit coordinate (i.e. 11SNT6963), the Add-In should:
- identify the nexus of the 69 easting and 63 northing in the NT grid square of the 11S grid zone
- display the complete MGRS Coordinate (11SNT6900063000) and the converted coordinate in any other identified coordinate system.

## Current Behavior

When using a four-digit coordinate (i.e. 11SNT6963), the Add-In currently:
- identifies the nexus of the 00069 easting and 00063 northing in the NT grid square of the 11S grid zone
- displays the complete but incorrect MGRS Coordinate (11SNT0006900063) and the converted incorrect coordinate in any other identified coordinate system.

**Essentially, the extra zeroes are being added to the front of the number, instead of the back.**
## Screenshots

![image](https://cloud.githubusercontent.com/assets/5016557/19402035/93b762ce-9213-11e6-8021-5ba8498c9bb1.png)

![image](https://cloud.githubusercontent.com/assets/5016557/19402288/29f21530-9215-11e6-943f-7586fe9d94b6.png)

## Steps to Reproduce (for bugs)

1. Start ArcGIS Pro
2. Navigate to Coordinate Conversion Add-In
3. Type in coordinate

## Context

Inaccurate coordinate conversion not only make this tool useless, but hazardous if used.

## Environment

- Coordinate Conversion 1.0.1
- ArcGIS Pro 1.3.1 and ArcGIS Pro 1.4 (build 6926)
- _ArcMap (10.4.1 and 10.5) works as intended_
- Windows 10

@nfeuerstein @lfunkhouser @karlterrey FYI

**Comment by joebayles** [comment]
Copied from https://github.com/ArcGIS/solutions-desktop-templates/issues/271

**Comment by nfeuerstein** [comment]
Thank you Joe.  Added the showstopper tag and adding to backlog to be addressed next sprint.

**Comment by mfunk** [comment]
@lfunkhouser @nfeuerstein 
This will be fixed in the coordinate-conversion-addin-dotnet repo:
https://github.com/Esri/coordinate-conversion-addin-dotnet

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/coordinate-conversion-addin-dotnet#137
