### ISSUE TITLE
Coordinate Conversion ArcGIS Pro Add-In Version Number

### ISSUE THREAD

**Issue by joebayles** [Esri/military-tools-for-arcgis#35]
The Add-In included in the Coordinate Conversion 1.0.1 download is labeled as 1.0. Not sure if this is:
- Incomplete number in the Add-In Installation Utility
- Wrong version

![image](https://cloud.githubusercontent.com/assets/5016557/19404955/4bc1cbb2-9227-11e6-81ee-1a612128b6e7.png)

FYI @nfeuerstein @lfunkhouser

**Comment by topowright** [comment]
@joebayles good catch. 

@nfeuerstein @lfunkhouser this should be added to the backlog or should it just be done outside the other work? Not sure how we are addressing bugs under the new system.

**Comment by nfeuerstein** [comment]
@topowright definitely added to the backlog.  Anyone can add something to the backlog under the "for review" section and I'll prioritize it appropriately.

**Comment by topowright** [comment]
@nfeuerstein Thanks for the info.

**Comment by topowright** [comment]
This has been added to the backlog for review.

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/coordinate-conversion-addin-dotnet#160
