### ISSUE TITLE
Holistic Testing - Visibility Widget - WAB 2.1

### ISSUE THREAD

**Issue by adgiles** [Esri/military-tools-for-arcgis#37]
Is this widget complete as I do not see any configuration options for adding an underlying elevation service, when I click the settings button I get the following error:

Uncaught TypeError: Cannot read property 'inputCoordinate' of undefined

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by topowright** [comment]
The visibility widget now has a configuration page: 

![image](https://cloud.githubusercontent.com/assets/5488313/21091800/727c903a-bffd-11e6-9d24-3809ae973a98.png)

@adgiles please verify.

**Comment by topowright** [comment]
Just for clarity the gp service should be the one that sets the elevation layer. the widget just needs to point to the gp service.

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/solutions-webappbuilder-widgets#716
