### ISSUE TITLE
Pro addin "Convert Coords" - inconsistent name

### ISSUE THREAD

**Issue by elinz** [Esri/military-tools-for-arcgis#39]
On the ribbon, the add-in is named "Convert Coords"; on the add-in interface it's named "Coordinate Conversion". Also spell the name out completely. There is obviously room for the complete name, as the other add-in's are spelled out completely,

![image](https://cloud.githubusercontent.com/assets/4635490/20015410/98e2b3be-a278-11e6-8c4b-2a763051280f.png)

## Expected Behavior

The add-in name on the ribbon should match the name on the add-in interface.

## Current Behavior

On the ribbon, the add-in is named "Convert Coords"; on the add-in interface it's named "Coordinate Conversion"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: Military Tools for ArcGIS built on 04 Nov 2016 09:06
* Environment name and version (e.g. Chrome 39, node.js 5.4): ArcGIS Pro 1.2. final (5023)
* Operating System and version (desktop or mobile): Windows 7 Enterprise 64 bit
* Link to your project:

**Comment by dhagens** [comment]
Fixed in ArcGIS_Pro_1.2 branch in coordinate-conversion-addin-dotnet repo

**Comment by elinz** [comment]
The fix for this issue was made and merged. I will verify on latest Pro SDK 1.2 build of the addin.

**Comment by elinz** [comment]
I installed the CoordinateConversion.esriAddInX file located in the build folder 12-07-2016_10\ArcGISPro\Addins\CoordinateConversion. Opened ArcGIS Pro 1.2 and add-in name matches the add-in dialog title as shown below:
![image](https://cloud.githubusercontent.com/assets/4635490/21029660/acb9d6aa-bd4f-11e6-85aa-9c110e52ce62.png)

Closing this issue and marking it "Done".
