### ISSUE TITLE
Recommend included doc to be in .pdf format instead of Word

### ISSUE THREAD

**Issue by elinz** [Esri/military-tools-for-arcgis#40]
Unless we are going to provide doc in compiled chm help files, I would recommend that we should release the doc in .pdf format. Not all machines where these tools are going to get deployed will have Microsoft Word.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by lfunkhouser** [comment]
Closing. Doc is published as a PDF.
