### ISSUE TITLE
Holistic Testing - Coordinate Conversion Tool - ArcGIS Pro 1.2

### ISSUE THREAD

**Issue by abrowning80** [Esri/military-tools-for-arcgis#47]
## Expected Behavior
Selection arrow for Coorrdinates when activated should allow the user to select where they want coordinates of.

## Current Behavior
As soon as the arrow is dragged on the map it takes the 1st coordinates it can and does not allow the user to select a different location.

## Steps to Reproduce (for bugs)

1.  Open up Coordinate conversion tool.
2.  Select Map point tool
3.  Move arrow over map, coordinates will be chosen as soon as the arrow gets on to the map.
4.

## Your Environment
* Version used: ArcPro 1.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version (desktop or mobile): Windows 8 desktop
* Link to your project:

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/coordinate-conversion-addin-dotnet#163
