### ISSUE TITLE
Visibility tool crashes Arc Pro v1.2

### ISSUE THREAD

**Issue by abrowning80** [Esri/military-tools-for-arcgis#50]
## Expected Behavior
Visibility tool enables user to calculate line of sight.

## Current Behavior
After the raster surface data has been added in and observer point need to be added.  When trying to add in the observer points ArcPro crashes.

## Steps to Reproduce (for bugs)
1.  Open Tool
2.  Load in raster data (SRTM30m data from resources folder)
3.  Select observer point selection arrow.
4.

## Your Environment
* Version used: ArcPro 1.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version (desktop or mobile): Windows 8 desktop
* Link to your project:

**Comment by Dbarnes1** [comment]
@abrowning80 this issue cannot be replicated with ArcGIS Pro 1.3 or 1.4, and we are no longer targeting Visibility for ArcGIS Pro 1.2. Closing.
