### ISSUE TITLE
Visibility Pro 1.2 LLOS & RLOS crashes with Map Point Tool

### ISSUE THREAD

**Issue by mfunk** [Esri/military-tools-for-arcgis#51]
The **Linear Line of Sight** (LLOS) tool crashes when clicking on the Map Point Tool next to either Observers or Targets.

## Expected Behavior
I'm expecting to set the observer or target locations on the map using the Map Point Tool. I should be able to click a location on the map, and have an observer/target point added to the dialog, and a graphic added to the screen.

## Current Behavior
Pro crashes when you click on the Map Point Tool next to either Observers or Targets.

## Steps to Reproduce (for bugs)
* Click Visibility
* Visibiltiy window appears with LLOS and RLOS tabs
* Select LLOS tab
* Add elevation data (from SRTM raster dataset -- n36.dt2)
	* On LLOS tab, the Input Surface automatically picks this up
* Select Map Point Tool next to Observers
CRASH

## Context
Not able to use the tool without this capability.

## Your Environment

- Version used: ArcGIS Pro 1.2.0 Final (Build 5023???)
- Operating System and version (desktop or mobile): Windows 8.1 64-bit (desktop)

**Comment by mfunk** [comment]
FYI ... this also happens with the **Map Point Tool** on the **RLOS** tab too.

**Comment by Dbarnes1** [comment]
@mfunk I was able to verify that this issue doesn't exist with the Pro 1.3 and 1.4 versions of the Visibility Add-In. Closing.
