### ISSUE TITLE
Military Tools Widget Issues in WAB 2.2

### ISSUE THREAD

**Issue by kgonzago** [Esri/military-tools-for-arcgis#52]
Issues with MT widgets in WAB 2.2 were logged in the https://github.com/Esri/military-tools-webappbuilder/ repo. Here is a list of issues found:

https://github.com/Esri/military-tools-webappbuilder/issues/108
https://github.com/Esri/military-tools-webappbuilder/issues/109
https://github.com/Esri/military-tools-webappbuilder/issues/110
https://github.com/Esri/military-tools-webappbuilder/issues/111
https://github.com/Esri/military-tools-webappbuilder/issues/112

**Comment by lfunkhouser** [comment]
Closing this issue. The 5 issues above have been moved to the Esri/solutions-webappbuilder-widgets repo
