### ISSUE TITLE
Coordinate Conversion - Export Enhancements

### ISSUE THREAD

**Issue by ACueva** [Esri/military-tools-for-arcgis#53]
These are issues I consider enhancements to the user experience.

Under the "Collect" tab:
- [ ] Rename "Save As" to "Export"
- [ ] Give some sort of feedback of a successful operation. i.e. for saving to a feature class/shapefile. "X amount of features were copied/created".

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/coordinate-conversion-addin-dotnet#161
