### ISSUE TITLE
Military Symbol Editor Pro 1.2 crashes

### ISSUE THREAD

**Issue by mfunk** [Esri/military-tools-for-arcgis#54]
Military Symbology Editor (MSE) crashes on ArcGIS Pro 1.2

## Expected Behavior
Not sure exactly what to expect. Just clicking around on the dialog. The search box is empty, and clicking **Add Favorite** should use something selected in the dialog, but since nothing selected the **Add Favorite** should probably be disabled

## Current Behavior
Clicking **Add Favorite** without a selection crashes ArcGIS Pro.

## Steps to Reproduce (for bugs)
* Click **Military Symbology Editor** on the *Military Tools* ribbon
* MSE window appears
	* 6 tabs
	* Three are enabled: Search, Modify, Favorites
	* Three are not enabled: Symbol, Label, Enter Coordinates
* Click **Search** (tab)
* Click **Add Favorite**
CRASH

## Your Environment
- Version used: ArcGIS Pro 1.2.0 Final (Build 5023???)
- Operating System and version (desktop or mobile): Windows 8.1 64-bit (desktop)

**Comment by mfunk** [comment]
FYI... if you search for a symbol, select something in the dialog, and THEN click **Add Favorite** the app does not crash Pro.

**Comment by elinz** [comment]
@csmoore I've tested this mornings fix. When I open a new project, click on Search tab and click on "Add Favorites" without anything selected in the Search list, Pro no longer crashes. Instead, the user will be prompted that the favorite is invalid. Think this is good to check into GitHub. I'll re-test/verify the bug when the change is in the Jenkins build of the add-in.

**Comment by csmoore** [comment]
@elinz  - many thanks for testing (and helping me diagnose - still not sure why I couldn't repro) - fixed in https://github.com/Esri/military-symbol-editor-addin-wpf/pull/112 & will be in next daily

**Comment by elinz** [comment]
Tested issue using latest tools built from Jenkins 10 Nov 2016 14:42
Verification test:
- Uninstall all the military tools addins using the UN-InstallMilitaryToolsForArcGISPro.bat
- Install the latest tools built by Jenkins using the InstallMilitaryToolsForArcGISPro.bat
- Opened ArcGIS Pro 1.2 final
- Created new project based on Map template
- Open Military Symbol Editor from the MILITARY TOOLS ribbon
- Click "Add Favorite". Result: ArcGIS Pro did not crash.
