### ISSUE TITLE
Distance and Direction Save As fails in 10.4.1

### ISSUE THREAD

**Issue by eogden** [Esri/military-tools-for-arcgis#55]
## Expected Behavior
Users should be able to select and save graphics once they have been created.

## Current Behavior
•	Within lines, circle and ellipse no feature class is created when users complete the save as a feature class function. 
•	When saving rings as a feature class, a feature class is created but when this is loaded back into the map nothing is displayed.
•	When saving Lines as shapefiles the result is a feature which is nothing like the original.
•	When saving circles or elipse as a shapefile the only circle which can be saved is the first one which was drawn none of the subsequent ones are saved. 

## Steps to Reproduce (for bugs)
1. Select Save As button
2. Complete Save As steps
3. Go to add in feature class or shapefile 

## Context
Unable to save graphics 

## Your Environment
* Version used: ArcMap10.4.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): IE
* Operating System and version (desktop or mobile): Windows 8.1 , 64 bit 
* Link to your project:

**Comment by jmhauck** [comment]
@nfeuerstein @kgonzago I have a commit ready for this issue but don't have the correct permissions in github to push a new branch that I could submit the pull request from.

**Comment by nfeuerstein** [comment]
@ACueva can you add @jmhauck to whatever team he needs to be on so that he can create a new branch and submit a pull request.  Thanks.

**Comment by ACueva** [comment]
@nfeuerstein @jmhauck I'll look into this right now

**Comment by ACueva** [comment]
@jmhauck You're an admin on the repo now.

**Comment by kgonzago** [comment]
@jmhauck Create a PR with your changes and assign it to me for review.

**Comment by Dbarnes1** [comment]
@kgonzago @jmhauck verified fixed. At 10.4.1, I can save lines, ellipses, circles, and rings as both features and kmz files and add them back into the map. The features that are saved out match the graphics drawn with the add in.
