### ISSUE TITLE
Distance and Direction - Graphics are not created for time and rate circles 

### ISSUE THREAD

**Issue by eogden** [Esri/military-tools-for-arcgis#58]
## Expected Behavior
When entering time and rate graphics should be produced when users click enter.

## Current Behavior
Entering time and rate causes a circle to be displayed but pressing enter never produces a graphic of the circle. 

## Steps to Reproduce (for bugs)
1. Click a point on the map 
2. Enter time an rate
3. Grey circle is displayed 
4. Click enter - red graphic is not drawn 

## Context
Trying to draw a graphic which includes time and rate

## Your Environment

* Version used: Desktop 10.4
* Environment name and version (e.g. Chrome 39, node.js 5.4): IE
* Operating System and version (desktop or mobile): Windows 8, 64bit
* Link to your project:

**Comment by jmhauck** [comment]
@kgonzago @nfeuerstein I am not able to reproduce this issue. Testing with 10.4.1.

**Comment by kgonzago** [comment]
Could not repro. Issue closed.
