### ISSUE TITLE
ArcMap documentation is all for 10.3

### ISSUE THREAD

**Issue by eogden** [Esri/military-tools-for-arcgis#59]
## Expected Behavior
All the ArcMap documentation is for 10.3 not 10.4

## Possible Solution
Create 10.4. documentation 

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by lfunkhouser** [comment]
Military Tools for ArcGIS in ArcMap has been updated to state that it supports ArcMap 10.3.1, 10.4, 10.4.1, and 10.5. The topics are version agnostic.
