### ISSUE TITLE
Highest points GP tool does not open - ArcPro 1.2

### ISSUE THREAD

**Issue by abrowning80** [Esri/military-tools-for-arcgis#60]
## Expected Behavior

For the Highest points, Linear Line of sight, Lowest Points, Radial Line of Sight GP tools do not open

## Current Behavior

Tool does not open with the following error

Tool has failed to open: C:\Users\admin\Desktop\ArcGISPro\Geoprocessing\Military_Tools.tbx\ _(name of GP tool)_

## Steps to Reproduce (for bugs)
1. Open tool
2.
3.
4.

## Your Environment

* Version used: ArcPro 1.2
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):  Windows 8 Desktop
* Link to your project:

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/military-tools-geoprocessing-toolbox#194
