### ISSUE TITLE
Coordinate Conversion - Increase number of decimal places for DD and DDM

### ISSUE THREAD

**Issue by elinz** [Esri/military-tools-for-arcgis#61]
For DD and DDM options in the "Add New Output Coordinate" we should increase the number of decimal places, we only display out to a single decimal place. This is approximately 6-7 nautical miles, which is too course and we should display out to two places. Especially since the map display units will display out to two decimal places.

![image](https://cloud.githubusercontent.com/assets/4635490/20024380/7891045a-a2a3-11e6-84a5-a51f0376efb7.png)

And update the Sample coordinate shown in the "Add New Output Coordinate" to match.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by jmccausland** [comment]
The "Input" group currently has no UI to configure it's format.  If you do not use "Edit Properties" the input format defaults to {0.0}.  Don't confuse the output format options with the input.

**Comment by nfeuerstein** [comment]
@jmccausland and @elinz can this issue be closed out?  Can the user use "edit properties" to set the decimal places?

**Comment by jmccausland** [comment]
There are no configuration properties to format the input decimal places.  Currently you can only change the type of coordinate.

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/coordinate-conversion-addin-dotnet#162
