### ISSUE TITLE
Distance and Direction - ArcGIS Pro 1.3.1 symbol change problem

### ISSUE THREAD

**Issue by fred3792** [Esri/military-tools-for-arcgis#62]
## Expected Behavior
 I should be able to change the symbol in either the Map view and have it apply in the Layout view.

## Current Behavior
I changed the symbol in the Map view, after creating a Ring using the Distance and Direction tools in ArcGIS Pro 1.3.1. The symbol didn't change in the Layout view. 

## Steps to Reproduce (for bugs)

1.	Open an existing project
2.	Save project as a new project
3.	Deleted unneeded layers and save
4.	Military Tools tab, click on Distance and Direction, click on Rings tab.
5.	Click on create point button, then select point, change Number of rings to 5, Distance Between Rings to 3000 and Number of Radials to 24, hit enter
6.	Save as Shapefile
7.	Change Symbol to red and line thickness of 3
8.	Changes happen in Map View but not in Layout view

## Context
I cannot change the symbol to make the graphic I want.

## Your Environment

* Version used: ArcGIS Pro 1.3.1
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
Intel Core i7, 2.3 GHz
16 GB RAM
64-bit OS, x64-based processor
Windows 8.1 Enterprise
* Link to your project: 
Link to screen captures https://esri.box.com/s/vvuo4xvpnyt3b8516wpl8889oqltn354

**Comment by Dbarnes1** [comment]
@fred3792 @nfeuerstein I think that this issue might be a result of not properly activating and deactivating the layout view with the exported shapefile. I tested this with Pro 1.4 and this seems to be working properly. If you want to go over the workflow let me know. 

At step 7, where you change the symbology of your shapefile, the symbology should automatically reflect those changes in the layout view, but you may need to activate the map in the layout view to make sure. I'm going to add verify tag.

**Comment by pHill5136** [comment]
@fred3792 @Dbarnes1 I tested this in 1.3 and it works as expected. The problem may have been neglecting to clear the graphic which is displayed on top of the feature layer.
