### ISSUE TITLE
"Add Favorites" in Military Symbol Editor allows duplicates to be added to favorites list

### ISSUE THREAD

**Issue by elinz** [Esri/military-tools-for-arcgis#63]
Repeatedly clicking the "Add Favorites" button in the Military Symbol Editor adds duplicates of the selected symbol.

## Expected Behavior

The editor shouldn't allow duplicates of the same exact symbol to be added to the favorites list.

## Current Behavior

Repeatedly clicking the "Add Favorites" button in the Military Symbol Editor adds duplicates of the selected symbol.

## Steps to Reproduce (for bugs)

1. Perform search for a symbol, such as Infantry, and select one from list
2. Click "Add Favorites", verify that symbol was added to list in Favorites list.
3. With same symbol still selected, click "Add Favorites", examine Favorites tab, the list will now have a duplicate symbol.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mfunk** [comment]
* Testing on Pro 1.2 ()
* Install 12/8/2016 @ 5:20am build from Jenkins

1) Create new Pro map project.
2) Military Tools >> Military Symbol Editor
3) Select *Search* tab
4) In Search type *infantry*
5) Select **Movement and Maneuver : Infantry : Amphibious : Friend** from resulting list
6) Select **Add Favorite** button
7) Select *Favorite* tab, my new symbol is in the list
8) Select *Search* tab, results are still there and symbol is still selected.
9) Select **Add Favorite** button twice
10) Select *Favorite* tab, now I have 3 symbols...

![image](https://cloud.githubusercontent.com/assets/3093182/21017341/e6cc67ae-bd1d-11e6-9e30-879240ee37ca.png)

**Comment by csmoore** [comment]
Created PR: https://github.com/Esri/military-symbol-editor-addin-wpf/pull/115 

That adds a check & issue warning if identical favorite:

![image](https://cloud.githubusercontent.com/assets/3090809/21055800/e706ea58-be00-11e6-9cb2-fdc199f86dff.png)

**Comment by mfunk** [comment]
Retesting with fix....

1. Military Tools >> Military Symbol Editor
2. Select *Search* tab
3. In Search type *infantry*
4. Select **Movement and Maneuver** : **Infantry** : **Amphibious** : **Friend** from resulting list
5. Select **Add Favorite** button
6. Select _Favorites_ tab, my new symbol is in the list
7. Back to _Search_, symbol is still selected, click **Add Favorite** again... Error Adding Favorite...

![image](https://cloud.githubusercontent.com/assets/3093182/21103818/d144bca6-c038-11e6-8f42-fdc8679d5543.png)

8. Click **OK** on error.
9. Click _Favorites_ tab..... only one symbol is there.
