### ISSUE TITLE
Visibility Add-In in Pro 1.4 doesn't throw an error when working with raw imagery layer

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-tools-for-arcgis#64]
Testing Linear Line of Sight in Pro 1.2 with raw imagery data, not with projected imagery, and the tool doesn't run but I also don't get an error prompt saying I need to project my imagery. I'd like to see something like this (from arcmap 10.3.1):

![image](https://cloud.githubusercontent.com/assets/13024357/20317250/16b33850-ab1a-11e6-94d2-bf66d5a9de9d.png)

**Comment by Dbarnes1** [comment]
Updated- this issue is still valid for Pro 1.4, hopefully we can get this in for January release.

**Comment by dhagens** [comment]
@Dbarnes1, could you provide access to the imagery that you were using to test this with?  I'd like to test with the same if possible.

**Comment by Dbarnes1** [comment]
@dhagens has access now

**Comment by topowright** [comment]
@Dbarnes1 I have tested this and it is no longer an issue. Can you verify this in ArcGIS Pro 1.4 using the latest build of the add-in?

**Comment by Dbarnes1** [comment]
![image](https://cloud.githubusercontent.com/assets/13024357/21112806/fd6d1abc-c05b-11e6-9deb-8d74ca90823a.png)


verified in Pro 1.4, closing.
