### ISSUE TITLE
Military Tools for ArcGIS Components drop downs dont appear properly with Pro 1.4 Dark Theme

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-tools-for-arcgis#66]
I was testing Distance and Direction in Pro Holistic today, and was using 1.4 Dark Theme. While the rest of the panes look really slick, our add-ins, particularly the drop-downs (text only appears as you pan over the drop down), look bad. I'm not sure if we are pulling the UI from Pro or whether we configured the UI of the add-ins ourselves. Either way, we should tackle this (unless users won't change their instances of Pro to dark theme).

![image](https://cloud.githubusercontent.com/assets/13024357/20817697/0f0862bc-b7de-11e6-84e5-69ed1a660cfe.png)

##Steps to Repro
Install Pro 1.4 (this was found on build 7128)
Add Military Tools Add-Ins
Under the App Options, under Personalize, choose the dark theme.
Open the Military Tools Add-Ins

**Comment by joebayles** [comment]
Closing because this is a duplicate.
