### ISSUE TITLE
Distance And Direction: Radials for rings are not created at the correct length in ArcGIS Pro

### ISSUE THREAD

**Issue by elinz** [Esri/military-tools-for-arcgis#67]
When I use the Rings function on the Distance And Direction addin the length of the radials created do not have the correct length. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/4635490/20897633/fb6e6506-bad7-11e6-9ae6-bf2d375d5817.png)

## Expected Behavior

The length of the radials created should match the radius of the outer most ring.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: ArcGIS Pro 1.3.0 final
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Windows 8.1 Enterprise 64 bit
* Link to your project:

**Comment by elinz** [comment]
We know that at least for 1.2 and 1.3 we can't create geodetic lines so the "Number of Radials" parameter should be hidden/disabled or removed.

**Comment by kgonzago** [comment]
@nfeuerstein @topowright Should we remove Radials from Distance and Direction Pro 1.2/1.3 entirely?

**Comment by nfeuerstein** [comment]
@kgonzago - Distance and Direction is dead in 1.2 all together.  For 1.3, we should probably remove radials if there is no way to fix it.  It seems to me that 1.3 doesn't support radials.

**Comment by Dbarnes1** [comment]
@nfeuerstein would an alternative to removing radials in 1.3 be to include a known issue about radials not working properly in our documentation? This is what we are currently doing in regards to line creation in the add-in. See this PR: https://github.com/ArcGIS/arcgis-solutions-website/pull/4608/files

**Comment by nfeuerstein** [comment]
@Dbarnes1 yes, that is an alternative.  The bottom line is that lines aren't supported, we can either document that geodesic lines aren't supported or we can remove the option.  Which is more feasible?

**Comment by Dbarnes1** [comment]
@nfeuerstein I think updating the documentation with a known issue for pro 1.3, and then removing the functionality for lines and radials in pro 1.4 would be the most suitable option considering the current technical limitations.

**Comment by nfeuerstein** [comment]
Sounds like a plan.  Any issues with that @kgonzago?

**Comment by kgonzago** [comment]
I like that plan. This is similar to #68. Once issue persists when testing with Pro 1.4, the line and radials will be removed entirely.

**Comment by elinz** [comment]
@kgonzago I installed the latest build of Military Tools for ArcGIS that I believe was built on 1.3 SDK and the same issue exists.

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/distance-direction-addin-dotnet#181
