### ISSUE TITLE
Distance And Direction: Radials for rings are not created as geodetic lines in ArcGIS Pro

### ISSUE THREAD

**Issue by elinz** [Esri/military-tools-for-arcgis#68]
The radials are not created as geodetic lines. 

We know that at least for 1.2 and 1.3 we can't create geodetic lines so the "Number of Radials" parameter should be hidden/disabled or removed.

![image](https://cloud.githubusercontent.com/assets/4635490/20897769/8e42eb72-bad8-11e6-8a93-bdcaa096d51b.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: ArcGIS Pro 1.3.0 final
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Windows 8.1 Enterprise 64 bit.
* Link to your project:

**Comment by kgonzago** [comment]
@elinz Can you test this with Pro 1.4? If issue persists, we will have to remove this functionality from the release.

**Comment by elinz** [comment]
@kgonzago I installed the latest build Military Tools for ArcGIS that i believe was built on 1.3 SDK and I get the same incorrect results.

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/distance-direction-addin-dotnet#180
