### ISSUE TITLE
Distance and Direction WAB widget: Ellipse tool does not create any ellipse graphics

### ISSUE THREAD

**Issue by elinz** [Esri/military-tools-for-arcgis#75]
Ran the ellipse tool from the Distance and Direction widget with the parameters shown in the screenshot below, and no ellipse was created. The only thing drawn on the map was the graphic to indicate the center point:
![image](https://cloud.githubusercontent.com/assets/4635490/20906871/2c502728-baff-11e6-8f6d-18f89b5553da.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: Web App Builder 2.2
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by ACueva** [comment]
This issue was moved to Esri/solutions-webappbuilder-widgets#687
