### ISSUE TITLE
Errors in the Visibility Add-in Labels for Visible Observers does not show up 

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-for-arcgis#76]
When running the visibility LOS tool in  the ArcGIS Pro add-in there should be a label showing how many observers can see a target. Currently This does not show up

## Expected Behavior
I would expect any target that is green be numbered with at least one

## Current Behavior
No label is being generated

## Possible Solution
Unclear. This works in ArcGIS Pro 1.3 , but not in ArcGIS Pro 1.4

## Steps to Reproduce (for bugs)

1.Choose at least one target 
2.Choose multiple observers (make sure the observer can see the target)
3.Run the LOS tool
4.

## Your Environment
Using ArcGIS Pro 1.4 - alpha

**Comment by topowright** [comment]
@nfeuerstein adding you for awareness

**Comment by dhagens** [comment]
The following are my findings for the labeling in Pro 1.4

In Pro 1.3, the label expression engine is either defaulted to VBScript or is smart enough to know what kind of expression is being used and sets it automatically.  In Pro 1.4, the expression engine defaults to Arcade.  By programatically setting the expression engine in the code to VBScript, the following label expression does validate correctly:

                                 Function FindLabel ( [NumOfObservers] )
                                       If (CInt([NumOfObservers])>0) Then
                                           FindLabel = [NumOfObservers]
                                       else
                                           FindLabel = ""
                                       End If
                                    End Function

Unfortunately the label is never displayed.  I tried modifying the expression several different ways but cannot get the label to show up.  I also tried exporting the working expression in Pro 1.3 and importing the that expression in Pro 1.4.  Again, the expression validates fine, but does not display a label.

**Comment by dfoll** [comment]
@topowright check out @mfunk latest comments on https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/159 and https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/157

**Comment by topowright** [comment]
@mfunk @dfoll I just spoke to core and this is a major issue for them that they are going to get started on now. The issues that we found are as follows:  

1. The labeling tool is not setting the language to the type that is being passed. For our tool that should be automatically set to  VisualBasic, but instead it is staying on Arcade, which i think is default. 

2. The location of the label is not being set even though the tool passes the CenterPoint parameter.

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/visibility-addin-dotnet#107
