### ISSUE TITLE
Coordinate Conversion: After entering coordinates and hitting return, Pro does not "flash" the coordinate location on the map

### ISSUE THREAD

**Issue by elinz** [Esri/military-tools-for-arcgis#77]
In the ArcMap addin, when you enter coordinates and hit return, a crosshair(?) is flashed on the map display to show you where the entered coordinate is. If the coordinate location is not located in the current extent, the addin pans and centers the coordinate in the map. The ArcGIS Pro addin does none of this.

This is an import function to have, as it helps the user verify that they have entered the expected coordinate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by kgonzago** [comment]
@elinz Which version of Pro were you testing with? Which add-in was tested?

**Comment by kgonzago** [comment]
@jmccausland verified bug exists in Pro 1.3 and fix will be applied.

**Comment by kgonzago** [comment]
@elinz Can you verify fix when you have a moment?

**Comment by elinz** [comment]
@kgonzago I build manually fire off Jenkins build and test.

**Comment by elinz** [comment]
@kgonzago @jmccausland I tested and now the cross hairs are displayed, however, there are a couple of issues:
1. When I enter in a coordinate pair and hit return in order for the location to be flashed on the map, the Map Point Tool is enabled, so if I happen to place the mouse over the map I now lose the coordinate I entered.
2. When I enter in a coordinate pair, for example 40.0220N 101.9971W, the crosshairs are displayed in the correct location, however, the point graphic that is displayed is not centered on the crosshairs. In this example, 40.0220N 101.9971W, is approximately in the center of the continental US. The crosshairs display at this location, but the point graphic is display off the northwest coast of Venezuela.
NOTE: sometimes the point is centered on the crosshairs.
This might be able to reproduce this by:
- Zooming out to world extent.
- Enter 40.0220N 101.9971W and hit return (the point and crosshairs locations match)
- Now pan to the East so that the center of the US is just on the left edge of map display.
- Now reenter same coordinates, 40.0220N 101.9971W, and hit return. (the crosshairs display at the correct location, but the point displays in Antarctica.

**Comment by jmccausland** [comment]
1. Known issue, the "flash" is a tool overlay and only works when tool is active.

2. Usually the point graphic displays incorrectly the first time.  Another known issue, I believe it to be a core issue and there is no workaround ATM.

**Comment by elinz** [comment]
If the "flash" only works when the Map Point Tool is active, then I think we have to consider reverting this change so that flash does not work. I think this is going to lead to problems where the user end up capturing incorrect coordinates. 

Thoughts from anybody?

**Comment by elinz** [comment]
@kgonzago @jmccausland No response back to my question above.  If the only way to get the "flash" to work in ArcGIS Pro is to make the Map Tool active then we should revert the fix. Having this tool automatically made active is "dangerous". Users will type in a coordinate, hit return, the coordinate is converted, then if they happen to move the mouse over the map display, the output coordinates will automatically update (because the tool was made active without user action) based on the position of the cursor. The user may not notice this and copy the output coordinates which they thought were based on the coordinates they typed in and they would be copying the incorrect coordinates.

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/coordinate-conversion-addin-dotnet#155
