### ISSUE TITLE
Using the dark theme in ArcGIS Pro creates issues with drop down menus

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-for-arcgis#79]
Using the dark theme in ArcGIS Pro creates issues with drop down menus
## Expected Behavior
I would want to see all of the parameters. 

## Current Behavior
![image](https://cloud.githubusercontent.com/assets/5488313/21030557/17f3e4c8-bd97-11e6-83b4-723f54910247.png)

## Possible Solution
Create a solid background for the drop down menu

## Steps to Reproduce (for bugs)

1. Select a drop down menu on any of the tabs
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Dbarnes1** [comment]
@topowright kind of a duplicate: https://github.com/Esri/military-tools-for-arcgis/issues/66

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-tools-pro-single-add-in#15
