### ISSUE TITLE
Clear Graphics buttons on Distance and Direction Add-in delete all graphics

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-for-arcgis#80]
Clear Graphics buttons on Distance and Direction Add-in delete all graphics

## Expected Behavior
Each Graphics button only deletes the graphics from that tab

## Current Behavior
All graphics are delted when using the Clear Graphics button

## Steps to Reproduce (for bugs)

1.Create graphics on two differnt tabs
2. click the Clear Graphics button
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/distance-direction-addin-dotnet#177

**Comment by dhagens** [comment]
Ready for testing
