### ISSUE TITLE
Overwriting layers produces Issues for Visibility 

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-for-arcgis#82]
Currently the Visibility add-in is configured to overwrite the same four layers for LLOS and the same two layers for RLOS. 

## Expected Behavior
Layers overwrite and tools run properly

## Current Behavior
Layers do not write to TOC
Layers do not write to the default database

## Possible Solution
Have unique names for all layers being written from each tool. 
RLOS - Observers
RLOS - Targets
as an example
## Steps to Reproduce (for bugs)

1.Run the LLOS tool
2.Run the RLOS tool
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/visibility-addin-dotnet#103
