### ISSUE TITLE
Dark theme in Pro 1.4 - White and black backgrounds for text

### ISSUE THREAD

**Issue by joebayles** [Esri/military-tools-for-arcgis#88]
There are input text boxes and non-input text boxes that have both white and black backgrounds.
![image](https://cloud.githubusercontent.com/assets/5016557/21825113/38d991d8-d737-11e6-9766-e4c20b13ab71.png)

When the above text boxes are empty, I think they look a little broken (even though they work just fine).
![image](https://cloud.githubusercontent.com/assets/5016557/21825145/615ef936-d737-11e6-8194-ea7d2ab1ff0b.png)

Another example:
![image](https://cloud.githubusercontent.com/assets/5016557/21825213/a94f5c04-d737-11e6-8bd9-da8bbae05ea2.png)

Suggest these get harmonized across the add-in.

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-tools-pro-single-add-in#14
