### ISSUE TITLE
Dark theme in Pro 1.4 - Radial Buttons have no label

### ISSUE THREAD

**Issue by joebayles** [Esri/military-tools-for-arcgis#89]
![image](https://cloud.githubusercontent.com/assets/5016557/21825278/e7f8cf6c-d737-11e6-8b9c-0efe52090fc1.png)

Assuming it's similar to #66 and #79 issue regarding drop-down menus, but in the Save As dialog, the options can't be read. I can't tell if they are there and white text, or not there.

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-tools-pro-single-add-in#13
