### ISSUE TITLE
Distance and Direction - Save As not exporting relevant fields

### ISSUE THREAD

**Issue by ACueva** [Esri/military-tools-for-arcgis#91]
## Expected Behavior
I should see exactly what the addin displays:

![1-17-2017 3-46-46 pm](https://cloud.githubusercontent.com/assets/3093940/22044940/34239ebe-dccc-11e6-95a8-9a2328fc01db.png)

Starting Point
Ending Point
Distance/ Lenght
Angle

## Current Behavior
Save As- Export to Feature Class
![1-17-2017 3-38-26 pm](https://cloud.githubusercontent.com/assets/3093940/22044754/155e7702-dccb-11e6-8815-026e70bb2232.png)

Save As - Shapefile
![1-17-2017 3-41-40 pm](https://cloud.githubusercontent.com/assets/3093940/22044829/779d713e-dccb-11e6-95cb-12e9f08fa1bb.png)

## Steps to Reproduce (for bugs)
1. Create a line using map tool.
2. Click Save As
3. Select either Feature Class or Shapefile
4. Explore  (identify) item

## Context
I believe we have all this information, why not export it so the customer can use it?

## Your Environment
ArcGIS Pro 1.4

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/distance-direction-addin-dotnet#299
